name: Publish
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - uses: actions/checkout@v2

      - name: install packages
        run: npm install

      - name: check
        run: npm run check

      - name: build
        run: npm run build --production

      - name: publish
        run: |
          cd dist
          aws s3 rm --recursive s3://isaac-j-miller.com
          aws s3 cp --recursive --acl public-read . s3://isaac-j-miller.com
          aws cloudfront create-invalidation --distribution-id E3AJATXCNS28YL --paths '/*'
